apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-klaassen-cluster-installation
  namespace: openshift-operators
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/marcoklaassen/klaassen-ocp'
    path: gitops
  project: default
