apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-klaassen-cluster-installation
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/marcoklaassen/klaassen-ocp'
    path: gitops
  project: default
  ignoreDifferences:
    - group: user.openshift.io
      kind: User
      jsonPointers:
        - /groups
    - group: ""
      kind: ConfigMap
      name: custom-logo
      namespace: openshift-console
