kind: Secret
apiVersion: v1
metadata:
    name: github-oauth-config
    namespace: openshift-operators
    labels:
        app.kubernetes.io/part-of: che.eclipse.org
        app.kubernetes.io/component: oauth-scm-configuration
    annotations:
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
        che.eclipse.org/scm-github-disable-subdomain-isolation: "true"
type: Opaque
stringData:
    id: ENC[AES256_GCM,data:s9oo0FBVpDSMtw4sdMkN/Y58VsU=,iv:DlsYbBJBNn2z/hBGgHP2xuJO1juQMJNgSah1n+1xyh8=,tag:JAKz4zJbwnjwM6yH9cBRMQ==,type:str]
    secret: ENC[AES256_GCM,data:yHqgw5GIgmALH4Ohcn5NfJf3IpNb06j1aKKpo69L4mAXObF1YyUXOQ==,iv:vwaDUNpLtggnFYplKgwMjAyjOROduxDRcPGwpX3Oryg=,tag:dUStl6y2ethL88ekFaFVow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-22T13:40:23Z"
    mac: ENC[AES256_GCM,data:IDFx+IjC8Gkzf4HMjFbkkcE4qtJLCbgdEqk/YNAyVXCie0OaHiuhxukEA2g2EiveK7fMqoS/c7wACeUsaRGeJuivnkqVMhY1pTr9+vHwCRwMNV8oyXjSZexU0UBn6gLrHKDorFjxUsaX9mXN4SVhEXaYqUA4jLPs4+9zaxhrM4Y=,iv:qVvOgOV6QJTTa89aqZKLae2d+djkiJpvMXAFbdu7tDQ=,tag:TwJDIwgxSOnTyv0GyZzMog==,type:str]
    pgp:
        - created_at: "2024-05-22T13:40:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1FH4nk+hvMsARAApwXU0/dkM0ZYMCFpI2nB20bhGgLeqqyGeEA7xahFzNOJ
            hzJuKEMA/69aKnjKbR3nvr+rNmtIQozTYZPSdDspDV2NGQBnsAMDeFaX6MswxoVz
            IhZ4u0YO8QamP1Ngs2Y4vpf54EjIcAWEa3NYAJqxvnIsggWpjiuhnmRXDSOWeKDL
            MD9WCoNqjJQee5q1HDAC0DB1/MWpaBQDAJXf9JdoLa3khHR2vDFmtcjj+saFgKqA
            RF8bLE/udGPt4zuyS7kB8zgbIJMsCIE8SWzbalHviRf//r3S3un23wgU+AEu2BB7
            or99gF4rHzzd4JjLwLgT2vTKCDfjzlGRjwmlSLkVa0NKMg52RAEaBRWAy4h4RN09
            k5icA7Q4cj8bAe6cZGXIxQhaZii+Ln43edZPCNbtuy8vAydVAB77Jk065+/HweD/
            NOTRr7J6cTl39w05WbgtXRD44+FwnVsS356O0RhS5ILEu2YYInpVdZ1KHVAsfG16
            FL7oMzKOHML2GgYCcgswRydV0td6Rv7gEE7cBHqUDm0196EH/PEPlAeVMnaokRQu
            EHMXQTFLrU0/LBpW9ewlkHiJbJWqR+Cj2iny1vmd4flIjdeDMI+nSakIBx8/DfbN
            2+N+6i+8bavVM9BWEGgq1zcYWEiLjlEBOeeCORHWQKZP/y3cPJxgSw/4BpSW0e3U
            aAEJAhDOSn0Pwh1NdrWXoCYQ1agn9L6e5dqRsypFgoDguro8MRdu+pa6b6C8gMYR
            BIzFKzFm/CvO8RI0uMFdfXefcxewZ8C729EUZE+jJQDZSwQ5XAZPGi9TCE/GsSK2
            azmcyuuUJksr
            =uOqj
            -----END PGP MESSAGE-----
          fp: 2993FF2065E46521576A5FFF34181E40C6544217
    encrypted_regex: stringData
    version: 3.7.2
